name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *' # täglich 06:00 UTC

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch latest meta from mmonster
        run: |
          node -v
          npm -v
          npm run fetch:meta || echo "Fetcher failed, keep existing data.json"

      - name: Commit updated data.json if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json || true
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: update data.json from mmonster"

      - name: Push back to main (if updated)
        if: always()
        run: |
          git push || echo "Nothing to push"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
